# Generated by Django 3.1.6 on 2021-03-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('runTime', models.IntegerField()),
                ('trailer_url', models.CharField(max_length=200)),
                ('poster_url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField(unique=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50)),
                ('show_start_time', models.IntegerField()),
                ('status', models.CharField(choices=[('Running', 'RUNNING'), ('Finished', 'FINISHED'), ('Started', 'STARTED')], max_length=200)),
                ('price', models.IntegerField(null=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.cinema')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.movie')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('dob', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'Female'), ('O', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField()),
                ('movie_date', models.DateField()),
                ('seat_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.seat')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.show')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Action', 'ACTION'), ('Comedy', 'COMEDY'), ('Drama', 'DRAMA'), ('Horror', 'HORROR'), ('Romance', 'ROMANCE'), ('Thriller', 'THRILLER')], max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movie', models.ManyToManyField(to='Ticket.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movie', models.ManyToManyField(to='Ticket.Movie')),
            ],
        ),
    ]
