# Generated by Django 3.1.6 on 2021-03-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.FileField(blank=True, null=True, upload_to='media')),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'Female'), ('O', 'Other')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
