# Generated by Django 3.1.6 on 2021-03-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_genre_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movie_id',
        ),
    ]
