# Generated by Django 3.1.6 on 2021-03-25 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='director',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='show',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='Ticket.Cast'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ticket.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(default=None, to='Ticket.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='show',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ticket.show'),
        ),
    ]
