# Generated by Django 3.1.6 on 2021-03-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_auto_20210305_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.ManyToManyField(to='Ticket.Movie'),
        ),
    ]
