# Generated by Django 3.1.6 on 2021-03-25 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_auto_20210325_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ticket.cast'),
        ),
    ]
