# Generated by Django 3.1.6 on 2021-03-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0005_auto_20210305_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre',
        ),
    ]
