# Generated by Django 3.1.6 on 2021-03-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0006_remove_genre_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='categories',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('A', 'ACTION'), ('C', 'COMEDY'), ('D', 'DRAMA'), ('H', 'HORROR'), ('R', 'ROMANCE'), ('T', 'THRILLER')], max_length=200),
        ),
    ]
