# Generated by Django 3.1.6 on 2021-03-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0006_remove_movie_cast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
