# Generated by Django 3.1.6 on 2021-03-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0007_delete_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='show',
        ),
    ]
