# Generated by Django 3.1.6 on 2021-03-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0008_auto_20210326_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='show',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='show',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='movie_date',
        ),
        migrations.AddField(
            model_name='show',
            name='end_start_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cinema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ticket.cinema'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='location',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_no',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_start_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('Running', 'RUNNING'), ('Finished', 'FINISHED'), ('Started', 'STARTED')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='book_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_no',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.seat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='show',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.show'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
