# Generated by Django 3.1.6 on 2021-03-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0008_auto_20210305_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
