# Generated by Django 3.1.6 on 2021-03-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0009_auto_20210326_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat_no',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
