# Generated by Django 3.1.6 on 2021-03-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0009_delete_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'ACTION'), ('C', 'COMEDY'), ('D', 'DRAMA'), ('H', 'HORROR'), ('R', 'ROMANCE'), ('T', 'THRILLER')], max_length=200)),
                ('Movie', models.ManyToManyField(to='Ticket.Movie')),
            ],
        ),
    ]
