# Generated by Django 3.1.6 on 2021-03-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0010_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='Movie',
            new_name='movie',
        ),
    ]
