# Generated by Django 3.1.6 on 2021-04-05 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0012_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
