# Generated by Django 3.1.6 on 2021-04-08 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
        ('Ticket', '0015_auto_20210406_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.movie'),
            preserve_default=False,
        ),
    ]
