# Generated by Django 3.1.6 on 2021-04-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0017_show_cinema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='ticket_user',
        ),
    ]
