# Generated by Django 3.1.6 on 2021-04-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210406_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.FileField(blank=True, default='media/avatar.jpg', null=True, upload_to='images'),
        ),
    ]
