# Generated by Django 3.1.6 on 2021-03-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Action', 'ACTION'), ('Comedy', 'COMEDY'), ('Drama', 'DRAMA'), ('Horror', 'HORROR'), ('Romance', 'ROMANCE'), ('Thriller', 'THRILLER')], default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('runTime', models.IntegerField(default=None)),
                ('trailer_url', models.CharField(default=None, max_length=200)),
                ('poster_url', models.CharField(default=None, max_length=255, null=True)),
                ('casts', models.ManyToManyField(default=None, to='cinema.Cast')),
                ('director', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.director')),
                ('genre', models.ManyToManyField(default=None, to='cinema.Genre')),
            ],
        ),
    ]
